# https://github.com/gliderlabs/logspout
# https://github.com/looplab/logspout-logstash
# https://github.com/gliderlabs/logspout/tree/master/custom
FROM gliderlabs/logspout:v3.2.1
ENV SYSLOG_FORMAT rfc3164
